export const SET_RATING_TABLE = 'SET_RATING_TABLE';
export const SET_RATING_HEADER = 'SET_RATING_HEADER';
export const SET_STUDENT_FULL_INFO = 'SET_STUDENT_FULL_INFO';
export const SET_STUDENT_LOCAL_INFO = 'SET_STUDENT_LOCAL_INFO';
export const SET_SCHEDULE = 'SET_SCHEDULE';
